[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=70
filterwarnings =
    ignore::DeprecationWarning
env =
    USE_SQLITE=1
    PROJECTA_SECRET_KEY=test-key
    JWT_SIGNING_KEY=test-jwt-key
    PROJECTA_REDIS_URL=redis://localhost:6379/0
    PROJECTA_CELERY_BROKER=redis://localhost:6379/1
    PROJECTA_CELERY_BACKEND=redis://localhost:6379/2
